// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService finds unused images and previews cascade deletes for notes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CascadeDeleteNoteImages deletes images that are only used by the given note.
 * Shared images must not be deleted unless forceUniqueOnly is false (dangerous).
 * @param {string} notePath
 * @param {boolean} forceUniqueOnly
 * @returns {$CancellablePromise<void>}
 */
export function CascadeDeleteNoteImages(notePath, forceUniqueOnly) {
    return $Call.ByID(1532747312, notePath, forceUniqueOnly);
}

/**
 * ExportOrphans returns an orphan report as CSV or JSON text (dry-run friendly).
 * format: "csv" or "json" (case-insensitive).
 * @param {string} format
 * @returns {$CancellablePromise<string>}
 */
export function ExportOrphans(format) {
    return $Call.ByID(2873360866, format);
}

/**
 * ListOrphans returns COS images not referenced by any scanned Markdown file.
 * @returns {$CancellablePromise<$models.OrphanImage[]>}
 */
export function ListOrphans() {
    return $Call.ByID(1344204804).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PreviewCascadeDelete lists images tied to a note (and which are shared elsewhere).
 * @param {string} notePath
 * @returns {$CancellablePromise<$models.CascadeDeletePreview>}
 */
export function PreviewCascadeDelete(notePath) {
    return $Call.ByID(4108140932, notePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OrphanImage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CascadeDeletePreview.createFrom;
