// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService finds unused (orphan) COS images.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportOrphans returns an orphan report as CSV or JSON text (dry-run friendly).
 * format: "csv" or "json" (case-insensitive).
 */
export function ExportOrphans(format: string): $CancellablePromise<string> {
    return $Call.ByID(2873360866, format);
}

/**
 * ListOrphans returns COS images not referenced by any scanned Markdown file.
 */
export function ListOrphans(): $CancellablePromise<$models.OrphanImage[] | null> {
    return $Call.ByID(1344204804);
}
