// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService finds unused images and previews cascade deletes for notes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CascadeDeleteNoteImages deletes images that are only used by the given note.
 * Shared images must not be deleted unless forceUniqueOnly is false (dangerous).
 */
export function CascadeDeleteNoteImages(notePath: string, forceUniqueOnly: boolean): $CancellablePromise<void> {
    return $Call.ByID(1532747312, notePath, forceUniqueOnly);
}

/**
 * ExportOrphans returns an orphan report as CSV or JSON text (dry-run friendly).
 * format: "csv" or "json" (case-insensitive).
 */
export function ExportOrphans(format: string): $CancellablePromise<string> {
    return $Call.ByID(2873360866, format);
}

/**
 * ListOrphans returns COS images not referenced by any scanned Markdown file.
 */
export function ListOrphans(): $CancellablePromise<$models.OrphanImage[] | null> {
    return $Call.ByID(1344204804);
}

/**
 * PreviewCascadeDelete lists images tied to a note (and which are shared elsewhere).
 */
export function PreviewCascadeDelete(notePath: string): $CancellablePromise<$models.CascadeDeletePreview> {
    return $Call.ByID(4108140932, notePath);
}
