// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes local app settings to the UI.
 * Credentials stay in env / local config file; only non-secret status is returned.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigFilePath returns where vault settings are stored (for UI display).
 */
export function ConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(3180221696);
}

/**
 * GetConfig returns current config from env / persisted settings (no secrets).
 */
export function GetConfig(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(2320765359);
}

/**
 * SaveShowThumbnails persists whether the UI should load/cached thumbnails.
 * Default is off to avoid COS egress until the user opts in.
 */
export function SaveShowThumbnails(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4201525806, enabled);
}

/**
 * SaveVaultPaths updates which vault roots are scanned for Markdown references.
 * Paths are persisted under the user config directory.
 */
export function SaveVaultPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2365012054, paths);
}
