// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes local app settings to the UI.
 * Credentials stay in env / local config file; only non-secret status is returned.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns current config (stubs until implementation).
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function GetConfig() {
    return $Call.ByID(2320765359).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveVaultPaths updates which vault roots are scanned for Markdown references.
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SaveVaultPaths(paths) {
    return $Call.ByID(2365012054, paths);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
