// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * COSService lists and deletes objects on Tencent Cloud COS.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteImages deletes COS objects by key. Prefer dry-run / confirm in UI first.
 * @param {string[]} keys
 * @returns {$CancellablePromise<void>}
 */
export function DeleteImages(keys) {
    return $Call.ByID(3957060343, keys);
}

/**
 * ListImages returns objects under the configured prefix, newest upload first.
 * @returns {$CancellablePromise<$models.ImageObject[]>}
 */
export function ListImages() {
    return $Call.ByID(2761055860).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ImageObject.createFrom;
const $$createType1 = $Create.Array($$createType0);
