// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig is local settings for the UI (SecretKey is never included).
 */
export interface AppConfig {
    "cosBucket": string;
    "cosRegion": string;

    /**
     * e.g. "obsidian/"
     */
    "cosPrefix": string;
    "cosBaseURL": string;
    "vaultPaths": string[] | null;

    /**
     * VaultPathErrors are non-fatal startup checks (bad roots, missing .obsidian/).
     */
    "vaultPathErrors": string[] | null;
    "showThumbnails": boolean;

    /**
     * SecretID is returned so Settings can prefill; SecretKey is never returned.
     */
    "secretId": string;
    "secretIdSet": boolean;
    "secretKeySet": boolean;
}

/**
 * COSSettings is the writable COS identity from the Settings UI.
 * Empty SecretKey means leave the existing stored key unchanged.
 */
export interface COSSettings {
    "secretId": string;
    "secretKey": string;
    "cosBucket": string;
    "cosRegion": string;
    "cosPrefix": string;
    "cosBaseURL": string;
}

/**
 * ImageObject is one object in Tencent COS (PicGo uploads).
 */
export interface ImageObject {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}

/**
 * ImageRef links a COS image URL to Markdown files that reference it.
 */
export interface ImageRef {
    "url": string;
    "key": string;

    /**
     * absolute or vault-relative .md paths
     */
    "notes": string[] | null;
}

/**
 * OrphanImage is on COS but not referenced by any scanned Markdown file.
 */
export interface OrphanImage {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}
