// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig is local settings (loaded from env / config file; never commit secrets).
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("cosBucket" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cosBucket"] = "";
        }
        if (!("cosRegion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cosRegion"] = "";
        }
        if (!("cosPrefix" in $$source)) {
            /**
             * e.g. "obsidian/"
             * @member
             * @type {string}
             */
            this["cosPrefix"] = "";
        }
        if (!("cosBaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cosBaseURL"] = "";
        }
        if (!("vaultPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["vaultPaths"] = [];
        }
        if (!("showThumbnails" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showThumbnails"] = false;
        }
        if (!("secretIdSet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretIdSet"] = false;
        }
        if (!("secretKeySet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretKeySet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("vaultPaths" in $$parsedSource) {
            $$parsedSource["vaultPaths"] = $$createField4_0($$parsedSource["vaultPaths"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * CascadeDeletePreview lists images that would be removed when deleting a note.
 */
export class CascadeDeletePreview {
    /**
     * Creates a new CascadeDeletePreview instance.
     * @param {Partial<CascadeDeletePreview>} [$$source = {}] - The source object to create the CascadeDeletePreview.
     */
    constructor($$source = {}) {
        if (!("notePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notePath"] = "";
        }
        if (!("images" in $$source)) {
            /**
             * @member
             * @type {ImageObject[]}
             */
            this["images"] = [];
        }
        if (!("sharedWithOtherNotes" in $$source)) {
            /**
             * SharedWithOtherNotes: images also used elsewhere — default policy is keep.
             * @member
             * @type {ImageRef[]}
             */
            this["sharedWithOtherNotes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CascadeDeletePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CascadeDeletePreview}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField1_0($$parsedSource["images"]);
        }
        if ("sharedWithOtherNotes" in $$parsedSource) {
            $$parsedSource["sharedWithOtherNotes"] = $$createField2_0($$parsedSource["sharedWithOtherNotes"]);
        }
        return new CascadeDeletePreview(/** @type {Partial<CascadeDeletePreview>} */($$parsedSource));
    }
}

/**
 * ImageObject is one object in Tencent COS (PicGo uploads).
 */
export class ImageObject {
    /**
     * Creates a new ImageObject instance.
     * @param {Partial<ImageObject>} [$$source = {}] - The source object to create the ImageObject.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * bytes
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("uploadTime" in $$source)) {
            /**
             * UploadTime prefers timestamp parsed from PicGo key name
             * (e.g. obsidian/20231002222829.png); falls back to LastModified.
             * @member
             * @type {string}
             */
            this["uploadTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageObject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageObject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageObject(/** @type {Partial<ImageObject>} */($$parsedSource));
    }
}

/**
 * ImageRef links a COS image URL to Markdown files that reference it.
 */
export class ImageRef {
    /**
     * Creates a new ImageRef instance.
     * @param {Partial<ImageRef>} [$$source = {}] - The source object to create the ImageRef.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * absolute or vault-relative .md paths
             * @member
             * @type {string[]}
             */
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageRef}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField2_0($$parsedSource["notes"]);
        }
        return new ImageRef(/** @type {Partial<ImageRef>} */($$parsedSource));
    }
}

/**
 * OrphanImage is on COS but not referenced by any scanned Markdown file.
 */
export class OrphanImage {
    /**
     * Creates a new OrphanImage instance.
     * @param {Partial<OrphanImage>} [$$source = {}] - The source object to create the OrphanImage.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * bytes
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("uploadTime" in $$source)) {
            /**
             * UploadTime prefers timestamp parsed from PicGo key name
             * (e.g. obsidian/20231002222829.png); falls back to LastModified.
             * @member
             * @type {string}
             */
            this["uploadTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrphanImage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrphanImage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrphanImage(/** @type {Partial<OrphanImage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ImageObject.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ImageRef.createFrom;
const $$createType4 = $Create.Array($$createType3);
