// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig is local settings (loaded from env / config file; never commit secrets).
 */
export interface AppConfig {
    "cosBucket": string;
    "cosRegion": string;

    /**
     * e.g. "obsidian/"
     */
    "cosPrefix": string;
    "cosBaseURL": string;
    "vaultPaths": string[] | null;
    "showThumbnails": boolean;
    "secretIdSet": boolean;
    "secretKeySet": boolean;
}

/**
 * ImageObject is one object in Tencent COS (PicGo uploads).
 */
export interface ImageObject {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}

/**
 * ImageRef links a COS image URL to Markdown files that reference it.
 */
export interface ImageRef {
    "url": string;
    "key": string;

    /**
     * absolute or vault-relative .md paths
     */
    "notes": string[] | null;
}

/**
 * OrphanImage is on COS but not referenced by any scanned Markdown file.
 */
export interface OrphanImage {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}
