// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig is local settings for the UI (SecretKey is never included).
 */
export interface AppConfig {
    /**
     * Vault / Obsidian COS (Images, Orphans, vault URL matching).
     */
    "cosBucket": string;
    "cosRegion": string;

    /**
     * e.g. "obsidian/"
     */
    "cosPrefix": string;
    "cosBaseURL": string;
    "vaultPaths": string[] | null;

    /**
     * VaultPathErrors are non-fatal startup checks (bad roots, missing .obsidian/).
     */
    "vaultPathErrors": string[] | null;
    "showThumbnails": boolean;

    /**
     * Browse COS is a separate bucket for the Browse tab (preview only; no vault).
     */
    "browseCosBucket": string;
    "browseCosRegion": string;
    "browseCosBaseURL": string;

    /**
     * SecretID is returned so Settings can prefill; SecretKey is never returned.
     */
    "secretId": string;
    "secretIdSet": boolean;
    "secretKeySet": boolean;
}

/**
 * BrowseCOSSettings is the writable Browse-tab bucket (shares SecretId/Key with Vault COS).
 */
export interface BrowseCOSSettings {
    "cosBucket": string;
    "cosRegion": string;
    "cosBaseURL": string;
}

/**
 * BrowseListing is one folder level under a COS prefix (Delimiter=/).
 */
export interface BrowseListing {
    "prefix": string;

    /**
     * common prefixes (full keys, trailing /)
     */
    "folders": string[] | null;

    /**
     * Objects are all non-directory keys in this folder (images and other files).
     */
    "objects": ImageObject[] | null;
}

/**
 * COSBucketInfo is one bucket from the account-level List Buckets API.
 */
export interface COSBucketInfo {
    "name": string;
    "region": string;
    "creationDate"?: string;
}

/**
 * COSSettings is the writable Vault/Obsidian COS identity from the Settings UI.
 * Empty SecretKey means leave the existing stored key unchanged.
 */
export interface COSSettings {
    "secretId": string;
    "secretKey": string;
    "cosBucket": string;
    "cosRegion": string;
    "cosPrefix": string;
    "cosBaseURL": string;
}

/**
 * CompressOptions controls local recompression before a same-key COS overwrite.
 */
export interface CompressOptions {
    /**
     * Quality is 1–100 (default 80). JPEG: encoder quality. PNG: pngquant max quality (TinyPNG-style).
     */
    "quality": number;

    /**
     * MaxEdge is the max long-edge in pixels; 0 means no resize.
     */
    "maxEdge": number;
}

/**
 * CompressPreview is a dry-run recompress result for UI comparison (no upload).
 */
export interface CompressPreview {
    "key": string;
    "url": string;
    "originalSize": number;
    "compressedSize": number;
    "compressedDataURL": string;
    "width": number;
    "height": number;

    /**
     * jpeg | png
     */
    "format": string;
    "quality": number;
    "maxEdge": number;

    /**
     * Smaller is false when compressed size is not strictly less than original.
     */
    "smaller": boolean;
    "message": string;
}

/**
 * ImageObject is one object in Tencent COS (PicGo uploads).
 */
export interface ImageObject {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}

/**
 * ImageRef links a COS image URL to Markdown files that reference it.
 */
export interface ImageRef {
    "url": string;
    "key": string;

    /**
     * absolute or vault-relative .md paths
     */
    "notes": string[] | null;
}

/**
 * OrphanImage is on COS but not referenced by any scanned Markdown file.
 */
export interface OrphanImage {
    "key": string;
    "url": string;

    /**
     * bytes
     */
    "size": number;
    "lastModified": string;

    /**
     * UploadTime prefers timestamp parsed from PicGo key name
     * (e.g. obsidian/20231002222829.png); falls back to LastModified.
     */
    "uploadTime": string;
}
