// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VaultService scans Obsidian Markdown files for COS image URLs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FindNotesUsing returns Markdown files that reference the given image URL or key.
 * @param {string} urlOrKey
 * @returns {$CancellablePromise<string[]>}
 */
export function FindNotesUsing(urlOrKey) {
    return $Call.ByID(3529044061, urlOrKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScanReferences walks configured vault paths and maps image URL → note paths.
 * @returns {$CancellablePromise<$models.ImageRef[]>}
 */
export function ScanReferences() {
    return $Call.ByID(3979652790).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.ImageRef.createFrom;
const $$createType2 = $Create.Array($$createType1);
