// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VaultService scans Obsidian Markdown files for COS image URLs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FindNotesUsing returns Markdown files that reference the given image URL or key.
 */
export function FindNotesUsing(urlOrKey: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3529044061, urlOrKey);
}

/**
 * ReadNote returns the UTF-8 Markdown body for a note path under a configured vault.
 */
export function ReadNote(notePath: string): $CancellablePromise<string> {
    return $Call.ByID(2521865529, notePath);
}

/**
 * ScanReferences walks configured vault paths and maps image URL → note paths.
 */
export function ScanReferences(): $CancellablePromise<$models.ImageRef[] | null> {
    return $Call.ByID(3979652790);
}
